### ISSUE TITLE
SVG icons are not displaying correctly in Production

### ISSUE THREAD

**Issue by crickkills** [BoomTownROI/boomstrap#12]
Just realized that the recent boomstrap SVG migration is causing display issues for the Seller Leads pagination component in production.

You can see it here next to the Filter By Client dropdown in the subheader:
 
https://leads.boomtownroi.com/admin/SellerLeads/?tid=582#?leadTypes=&cat=none&addr=&city=&st=&zip=

Mark and I dug into this in detail and found the culprit here:

https://github.com/BoomTownROI/boomstrap/pull/10/files
Note that the .SVG icon file paths are relative, so when attempting to load this icon from /admin/SellerLeads this file will not be found.

**Comment by crickkills** [comment]
Cross link to http://jira.boomtownroi.com:8080/browse/SLR-331

**Comment by mcraiganthony** [comment]
Sorry for the delayed response @crickkills!

This isn't a Boomstrap issue. When Boomstrap is installed as a dependency in a project, Boomstrap's SVG assets should be copied to a location that makes sense in the scope of the project.

In our CRM, Boomstrap's SVGs will be likely be copied (via additional CRM build task) to the directory where we store all of our images. Therefore, SVG paths in the CRM won't be the same as the paths that you see in Boomstrap's documentation.

**Comment by mfunkie** [comment]
Then how do we fix this in the CRM?  We need configurable paths for the SVG or we need to deprecate the old angular components and keep them ficons

**Comment by mcraiganthony** [comment]
We just need to figure out where we want to place them in the CRM. I'd imagine that they'd live next to the 'images' directory. The path would be handled the same way we handle paths to images.

**Comment by mfunkie** [comment]
I dont think that solves the hard-coded image path problem

**Comment by mcraiganthony** [comment]
Ok. I'm following now. This will be the same thing we'll need to figure out for the React side.

**Comment by mcraiganthony** [comment]
Reverted to using "ficon" in Angular directives until we can figure out how to incorporate configurable SVG paths. This change has been implemented in v1.16.4.
